# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up environment variables
      run: |
        echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
        echo "LOG_FILE=app.log" >> $GITHUB_ENV
        echo "ENV=development" >> $GITHUB_ENV  # You can adjust this if needed

    - name: Check environment variables
      run: |
        echo "Checking environment variables..."
        printenv | grep LOG

    - name: Run Tests
      run: |
        # Run pytest and capture any errors
        pytest --maxfail=1 --disable-warnings -q

    - name: Lint Code with flake8
      run: |
        # Running flake8 to lint the code
        flake8 .

    - name: Show logs
      run: |
        # Display the log file to see if it was created
        cat app.log || echo "No log file created"
